# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('resume_pdf', models.FileField(upload_to='./resumes_folder')),
                ('marksheet_pdf', models.FileField(upload_to='./marksheets_folder')),
                ('document_pdf', models.FileField(upload_to='./documents_folder')),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('do_you_have_plans_for_higher_studies', models.BooleanField()),
                ('where_do_you_see_yourself_in_the_coming_two_years', models.TextField(max_length=300)),
                ('why_did_you_choose_engineering', models.TextField(max_length=300)),
                ('allowed', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
