# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0005_auto_20170826_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
