# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0008_auto_20170826_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('IT', 'IT'), ('MECH', 'MECH'), ('COMPS', 'COMPS'), ('ITI', 'ITI'), ('HM', 'HM')], default='IT', max_length=10),
            preserve_default=False,
        ),
    ]
